export const facilities = [
  "Taman",
  "Jogging Track",
  "CCTV",
  "Lapangan Voli",
  "Lapangan Bola",
  "Lapangan Basket",
  "Lapangan Bulu Tangkis",
  "Tempat Jemuran",
  "Kulkas",
  "Telepon",
  "Tempat Cuci",
  "Laundry",
  "Masjid",
  "Taman Bermain",
  "Kolam Renang",
  "Mesin Cuci",
  "Kompor",
  "Keamanan 24 Jam",
  "Kolam Ikan",
  "Backyard",
  "Kitchen Set",
  "Teras",
  "Wastafel",
  "Akses Parkir",
  "Lapangan Tenis",
  "Tempat Gym",
  "AC",
  "Water Heater",
  "One Gate System",
];

export const images = [
  "/image-1.jpg",
  "/image-2.jpg",
  "/image-3.jpg",
  "/image-4.jpg",
];
export const pointOfInterest = [
  "Sekolah",
  "Pusat Perbelanjaan",
  "Transportasi",
];
